version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: tictactoe-postgres
    ports:
      - '54322:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: tictactoe
    volumes:
      - tictactoe_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  tictactoe_pgdata:
