version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: realty-ai-postgres
    ports:
      - '54321:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: realty-ai
    volumes:
      - realty_ai_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  realty_ai_pgdata:
